version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: "avsp-postgres-${USER}"
    environment:
      POSTGRES_DB: avsp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "8001:5432"
    networks:
      - avsp-net

  minio:
    image: minio/minio:latest
    container_name: "minio-${USER}"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - avsp-net

  avsp-server:
    image: avsp-server
    container_name: "avsp-server-${USER}"
    depends_on:
      - postgres
      - minio
    volumes:
      - "${PWD}/../..:/app"
      - "vscode-server:/root/.vscode-server"
    ports:
      - "9100:9000"   # если приложение слушает 9000
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: waymo-processed
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: avsp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - avsp-net

volumes:
  minio-data:
  postgres-data:
  vscode-server:

networks:
  avsp-net:
    driver: bridge
